### ISSUE TITLE
Publish site for 2.7.2

### ISSUE THREAD

**Issue by michael-o** [codehaus-plexus/plexus-io#6]
I am having trouble to publish the site:

    [INFO] Working directory: /usr/home/mosipov/Projekte/plexus-io/target/checkout/target/scmpublish-checkout
    [ERROR] Failed to delete files from SCM: The git command failed. fatal: Pfadspezifikation 'src/test/resources/symlinks/src/symLinkToDirOnTheOutside/FileInDirOnTheOutside.txt' stimmt mit keinen Dateien überein
    
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 38.882 s
    [INFO] Finished at: 2017-05-10T23:31:26+02:00
    [INFO] Final Memory: 9M/61M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-scm-publish-plugin:1.1:publish-scm (default-cli) on project plexus-io: Failed to delete files from SCM: The git command failed. fatal: Pfadspezifikation 'src/test/resources/symlinks/src/symLinkToDirOnTheOutside/FileInDirOnTheOutside.txt' stimmt mit keinen Dateien überein -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following article

Can someone do this for me?

**Comment by plamentotev** [comment]
Given the fact that both Plexus Io and Plexus Archiver sites are out of date I assume there is some problem with the site publishing (there is even issue for that - codehaus-plexus/plexus-archiver#44). I'll take look at it tomorrow and see if I can help.

**Comment by michael-o** [comment]
I did use `scm-publish:publich-scm` and that's the result :-(

**Comment by plamentotev** [comment]
Hmm I can't even generate the site. What version of Maven are you using?

**Comment by michael-o** [comment]
I used 3.3.9. I had to upgrade MSITE first and add a lot of skips to report plugins.

**Comment by plamentotev** [comment]
Looks like you have to set the git branch to `gh-pages` - http://maven.apache.org/plugins/maven-scm-publish-plugin/various-tips.html

It should  be something like this

```xml
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-scm-publish-plugin</artifactId>
        <configuration>
          <content>${project.reporting.outputDirectory}</content><!-- mono-module doesn't require site:stage -->
          <scmBranch>gh-pages</scmBranch>          
        </configuration>
```

By default the scm publish plugin tries to publish in the master branch. t checkouts the master branch (or If I'm not wrong the default branch for the repo unless you specify branch name) in temp folder, copies the site output into it and deletes all files that are in the branch but not in the site (so it can remove obsolete files) using `git -rm`. That's why it tries to delete the src folder content(it does exist in the master branch but it's not part of the site). It fails because the plugin is confused by the symbolic links and tells git to delete file that do not exist. Looks like there might be a bug in the plugin as well.

**Comment by michael-o** [comment]
You are a magician. That's the issue. Please create a PR for master.
